- name: Create Homework Assignment project
  tower_project:
    name: "{{ proj_name }}"
    description: "Advanced Ansible Automation Homework Assignment Project"
    organization: "{{ org_name }}"
    state: present
    tower_config_file: "ansible.cfg"
    scm_type: git
    #scm_credential:
    scm_branch: master
    scm_url: "{{ github_repo }}"
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    tower_verify_ssl: no

- name: Machine Credentail to connect to workstation using openstack.pub
  tower_credential:
    name: Connect_to_workstation
    organization: "{{ org_name }}"
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    ssh_key_data: "{{ user_cred_path }}"
    username: "{{ user_cred_name }}"

- name: Create Inventory for the project
  command: |
    tower-cli inventory create -n "{{static_inventory_name}}" --organization "{{org_name}}"

- name: Create Group in static inventory
  command: |
    tower-cli group create --inventory "{{static_inventory_name}}"  --name {{group_name}}


- name: Add tower host to the static inventory
  tower_host:
    name: "{{host_name}}"
    description: "workstation"
    inventory: "{{static_inventory_name}}"
    state: present
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    tower_verify_ssl: no

- name: Associate workstation host to group
  command: |
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"


- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: "{{ org_name }}"
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    tower_verify_ssl: no
    ssh_key_data: /root/.ssh/mykey.pem
    username: "{{ opentlc_login }}"

- name: Remove secret (the private ssh key)
  file:
    name: /root/secret.pem
    state: absent
