- name: Create Homework Assignment project
  tower_project:
    name: "{{ proj_name }}"
    description: "Advanced Ansible Automation Homework Assignment Project"
    organization: "{{ org_name }}"
    state: present
    scm_type: git
    scm_branch: master
    scm_url: "{{ github_repo }}"
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    tower_verify_ssl: no

- name: Machine Credentail to connect to workstation using openstack.pub
  tower_credential:
    name: Connect_to_workstation
    organization: "{{ org_name }}"
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    ssh_key_data: "{{ user_cred_path }}"
    username: "{{ user_cred_name }}"

- name: Create Inventory for the project
  tower_inventory:
    name: "{{ static_inventory_name }}"
    description: "SCM inventory"
    organization: "{{org_name}}"
    state: present
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    tower_verify_ssl: no

- name: Create Group in static inventory
  tower_group:
    name: "{{ group_name }}"
    description: "SCM inventory group"
    inventory: "{{ static_inventory_name }}"
    state: present
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    tower_verify_ssl: no

- name: Add tower host to the static inventory
  tower_host:
    name: "{{host_name}}"
    description: "Workstation"
    inventory: "{{ static_inventory_name }}"
    state: present
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    tower_verify_ssl: no

- name: Associate workstation host to group
  command: |
    tower-cli host associate --host "{{ host_name }}" --group "{{ group_name }}"

- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: "{{ org_name }}"
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    tower_verify_ssl: no
    ssh_key_data: "{{ lookup('file', '/root/secret.pem') }}"
    # ssh_key_data: /root/.ssh/mykey.pem
    username: "{{ opentlc_login }}"
    validate_certs: no

- name: Remove secret (the private ssh key)
  file:
    name: /root/secret.pem
    state: absent
